const CONNECT = "CONNECT";
const AUTH = "AUTH";
const JOIN_ROOM = "JOIN_ROOM";
const LEAVE_ROOM = "LEAVE_ROOM";
const GET_ROOM = "GET_ROOM";
const START_GAME = "START_GAME";
const END_TURN = "END_TURN";
const UPDATE_GAME_STATE = "UPDATE_GAME_STATE";
const END_GAME = "END_GAME";
const REQUEST_RESET = "REQUEST_RESET";
const DECLINE_RESET = "DECLINE_RESET";
const ACCEPT_RESET = "ACCEPT_RESET";

module.exports = {
    CONNECT,
    AUTH,
    JOIN_ROOM,
    LEAVE_ROOM,
    GET_ROOM,
    START_GAME,
    END_TURN,
    UPDATE_GAME_STATE,
    END_GAME,
    REQUEST_RESET,
    DECLINE_RESET,
    ACCEPT_RESET
}