const READY = "READY";
const USERS_ONLINE = "USERS_ONLINE";
const ASSIGN_ROOM = "ASSIGN_ROOM";
const SET_GUEST_ID = "SET_GUEST_ID"; 
const UPDATE_ROOM = "UPDATE_ROOM";
const UPDATE_GAME = "UPDATE_GAME";
const SEND_RESET_REQUEST = "SEND_RESET_REQUEST";
const WAITING_RESPONSE = "WAITING_RESPONSE";
const DECLINED_RESET = "DECLINED_RESET";
const ACCEPTED_RESET = "ACCEPTED_RESET";
const REJOIN_QUEUE = "REJOIN_QUEUE";

module.exports = {
    READY,
    USERS_ONLINE,
    ASSIGN_ROOM,
    SET_GUEST_ID,
    UPDATE_ROOM,
    UPDATE_GAME,
    SEND_RESET_REQUEST,
    WAITING_RESPONSE,
    DECLINED_RESET,
    ACCEPTED_RESET,
    REJOIN_QUEUE
}