const TAKE_TURN = "TAKE_TURN";
const RESET = "RESET";
const SET_GAME_STATE = "SET_GAME_STATE";
const SELECT_SHIP = "SELECT_SHIP";
const SET_SHIP_HOVER_SQUARES = "SET_SHIP_HOVER_SQUARES";
const ROTATE_SHIP = "ROTATE_SHIP";
const UPDATE_PLACED_SHIPS = "UPDATE_PLACED_SHIPS";
const DISPLAY_READY_BUTTON = "DISPLAY_READY_BUTTON";

export default {
    TAKE_TURN,
    RESET,
    SET_GAME_STATE,
    SELECT_SHIP,
    SET_SHIP_HOVER_SQUARES,
    ROTATE_SHIP,
    UPDATE_PLACED_SHIPS,
    DISPLAY_READY_BUTTON
}