const TAKE_TURN = "TAKE_TURN";
const RESET = "RESET";
const SET_GAME_STATE = "SET_GAME_STATE";
const SELECT_SHIP = "SELECT_SHIP";
const SET_SHIP_HOVER_SQUARES = "SET_SHIP_HOVER_SQUARES";
const ROTATE_SHIP = "ROTATE_SHIP";

export default {
    TAKE_TURN,
    RESET,
    SET_GAME_STATE,
    SELECT_SHIP,
    SET_SHIP_HOVER_SQUARES,
    ROTATE_SHIP
}