const UPDATE_PLAYERS = "UPDATE_PLAYERS"
const SET_OPPONENT = "SET_OPPONENT";
const COUNTDOWN = "COUNTDOWN";
const START_GAME = "START_GAME";

export default {
    UPDATE_PLAYERS,
    SET_OPPONENT,
    COUNTDOWN,
    START_GAME
}