const COUNTDOWN = "COUNTDOWN";
const UPDATE_ROOM_STATE = "UPDATE_ROOM_STATE";
const RESET_ROOM = "RESET_ROOM";
const START_ROOM = "START_ROOM";

const RESET_REQUEST_PROMPT = "RESET_REQUEST_PROMPT";
const WAITING_RESPONSE_PROMPT = "WAITING_RESPONSE_PROMPT";
const DECLINE_PROMPT = "DECLINE_PROMPT";
const ACCEPT_PROMPT = "ACCEPT_PROMPT";
const RESET_UI = "RESET_UI";
const DISPLAY_ALERT = "DISPLAY_ALERT";


export default {
    COUNTDOWN,
    UPDATE_ROOM_STATE,
    RESET_ROOM,
    START_ROOM,
    RESET_REQUEST_PROMPT,
    WAITING_RESPONSE_PROMPT,
    DECLINE_PROMPT,
    ACCEPT_PROMPT,
    RESET_UI,
    DISPLAY_ALERT
}