const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
const HIDE_LOGIN_FORM = "HIDE_LOGIN_FORM";
const SHOW_REGISTER_FORM = "SHOW_REGISTER_FORM";
const HIDE_REGISTER_FORM = "HIDE_REGISTER_FORM";

const GET_ERRORS = "GET_ERRORS";

const SET_CURRENT_USER = "SET_CURRENT_USER";

export default {
    SHOW_LOGIN_FORM,
    SHOW_REGISTER_FORM,
    HIDE_LOGIN_FORM,
    HIDE_REGISTER_FORM,
    GET_ERRORS,
    SET_CURRENT_USER
}