const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
const HIDE_LOGIN_FORM = "HIDE_LOGIN_FORM";
const SHOW_REGISTER_FORM = "SHOW_REGISTER_FORM";
const HIDE_REGISTER_FORM = "HIDE_REGISTER_FORM";

const GET_ERRORS = "GET_ERRORS";

const SET_CURRENT_USER = "SET_CURRENT_USER";
const SET_CONNECTION = "SET_CONNECTION";

const UPDATE_ONLINE_USERS = "UPDATE_ONLINE_USERS";
const ASSIGN_ROOM = "ASSIGN_ROOM";
const ASSIGN_GAME_TYPE = "ASSIGN_GAME_TYPE";

export default {
    SHOW_LOGIN_FORM,
    SHOW_REGISTER_FORM,
    HIDE_LOGIN_FORM,
    HIDE_REGISTER_FORM,
    GET_ERRORS,
    SET_CURRENT_USER,
    SET_CONNECTION,
    UPDATE_ONLINE_USERS,
    ASSIGN_ROOM,
    ASSIGN_GAME_TYPE
}